version: '3'

services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/logs:/var/log/nginx
    networks:
      - nginx-nodejs-mysql-fullcycle
    depends_on:
      - nodejs
    ports:
      - 8080:8080

  nodejs:
    build:
      context: ./nodejs
    container_name: nodejs
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: nodejs
      DB_USER: root
      DB_PASS: root
    networks:
      - nginx-nodejs-mysql-fullcycle
    depends_on:
      - database

  database:
    image: mysql:5.7
    container_name: mysql
    restart: always
    command: --innodb-use-native-aio=0
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodejs
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nginx-nodejs-mysql-fullcycle

networks:
  nginx-nodejs-mysql-fullcycle:
    driver: bridge
